# Generated by Django 5.2.1 on 2025-05-12 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
