# Generated by Django 5.2.1 on 2025-05-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroup_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='meeting_time',
        ),
    ]
